apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Release.Namespace }}
---
apiVersion: v1
kind: Pod
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
  labels:
    ownerBy: {{ .Values.ownerBy }}
spec:
  containers:
  - name: container
    image: {{ .Values.image }}
    ports:
    - containerPort: 80
